### PR TITLE
Switch from fclabels to lens

### PR DESCRIPTION
**Pull request by np**
This is done without actually depending on the lens package!

### CODE REVIEW

**Comment by ethercrow** [comment]
Current yi in hackage depends on pointedlist <0.6, so I've bumped version to 0.6.

I've used Nicolas' changes to port current yi master to using lens: https://github.com/ethercrow/yi/tree/lens-take2

**Comment by acertain** [comment]
Whats the status on merging this?

**Comment by jeffwheeler** [comment]
Sorry, I'm currently traveling internationally without my computer. I'll return around January 5th and will happily apply the patch at that time.

Thanks for the improvement!

Jeff

**Comment by jeffwheeler** [comment]
I no longer have my Haskell development environment setup. Would anybody be willing to upload this to Hackage?

Thank you.

**Comment by acertain** [comment]
@jeffwheeler Could you give fread2281 on hackage upload privileges?

**Comment by acertain** [comment]
@jeffwheeler [Here is the .tar.gz produced by cabal sdist, if you would rather upload it yourself](http://cl.ly/T8gU)

**Comment by acertain** [comment]
@jeffwheeler That is, I'd be willing to upload it, but you'd need to add me to the maintainer group.

**Comment by jeffwheeler** [comment]
Sure. Please wait until this weekend when I return from my winter vacation out of the country.

Jeff

**Comment by jeffwheeler** [comment]
Carter,

I've uploaded your tarball and added you to the list of maintainers so you can upload in the future if you wish. You're welcome to consider your own copy of the repo the "master" if you like.

Sorry for being slow, still on vacation. ;)

Jeff

**Comment by acertain** [comment]
@jeffwheeler thanks!

**Pull request merged**
